//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunchIntelligence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LI_BI_MonthlyIms
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string ValueType { get; set; }
        public string Region { get; set; }
        public string BusinessArea { get; set; }
        public string Country { get; set; }
        public string Product { get; set; }
        public Nullable<double> Value { get; set; }
    }
}
